courses/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'courses'
# We are defining the URL patterns for the courses app and linking them to the views
# Also, we are serving the media and static files in development
# settings variables comes from settings.py file
urlpatterns = [
    # Create a path object defining the URL pattern to the index view
    path(route='', view=views.index, name='index'),
    path(route='date', view=views.get_date, name='date'),
    path(route='course/<int:course_id>/enroll', view=views.enroll, name='enroll'),
    path(route='course/<int:course_id>', view=views.course_details, name='course_details')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_app/urls.py
from django.contrib import admin
from django.urls import path, include
# Import the settings module from django.conf where DJANGO_SETTINGS_MODULE is defined in asgi.py and wsgi.py
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models
from django.utils.timezone import now

# User model
class User(models.Model):
    # CharField for user's first name
    first_name = models.CharField(
        null=False, 
        max_length=30,
        default='john'
    )
    # CharField for user's last name
    last_name = models.CharField(
        null=False,
        max_length=30,
        default='doe'
    )
    # CharField for user's date for birth
    dob = models.DateField(
        null=True
    )

    # Create a toString method for object string reprensen
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

# Instructor model that inherits from User
class Instructor(User):
    full_time = models.BooleanField(
        default=True
    )
    total_learners = models.IntegerField(
        default=0
    )

    # Create a toString method for object string reprensentation
    def __str__(self):
        return "First name: " + self.first_name + ", " + \
                "Last name: " + self.last_name + ", " + \
                "Full time: " + str(self.full_time) + ", " + \
                "Total learners: " + str(self.total_learners)

# Learner model
class Learner(User):
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_links = models.URLField(max_length=200)

    # Create a toString method for object string reprensentation
    def __str__(self):
        return "First name: " + self.first_name + ", " + \
                "Last name: " + self.last_name + ", " + \
                "Date of Birth: " + str(self.dob) + ", " + \
                "Occupation: " + self.occupation + ", " + \
                "Social links: " + self.social_links

# Course model
class Course(models.Model):
    name = models.CharField(
        null=False,
        max_length=100,
        default='online course'
    )
    # dependecy of Pillow module
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=500)
    pub_date = models.DateField(default=now)
    # Many to many relationship with Instructor
    instructors = models.ManyToManyField(Instructor)
    learners = models.ManyToManyField(Learner, through='Enrollment')    
    total_enrollment = models.IntegerField(default=0)
    # Create a toString method for object string reprensentation
    def __str__(self):
        return f'Name: {self.name}, Description: {self.description}'
    
# Lesson model
class Lesson(models.Model):
    title = models.CharField(
        max_length=200,
        default='title'
    )
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
    content = models.TextField()

# Enrollment model
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
    ]
    # Add a learner foreign key
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
    # Add a course foreign key
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    # Enrollment date
    date_enrolled = models.DateField(default=now)
    # Enrollment mode
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import date
from .models import Course
from django.conf import settings
from django.http import Http404

# Create your views here.
def index(request):
    context = {}
    if request.method == 'GET':
        # get the top 10 courses with the highest enrollment
        courses = Course.objects.order_by('-total_enrollment')[:10]
        context['courses'] = courses
        context['MEDIA_URL'] = '/static'+ settings.MEDIA_URL
        return render(request, 'courses/course_list.html', context)
    
    
def get_date(request):
    today = date.today()
    template = "<html>" \
                "Today's date is {}" \
               "</html>".format(today)
    return HttpResponse(content=template)

def enroll(request, course_id):
    if request.method == 'POST':
        # First try to read the course object
        # If could be found, raise a 404 exception
        course = get_object_or_404(Course, pk=course_id)
        course.total_enrollment += 1
        course.save()
        # always return an HttpResponseRedirect after successfully dealing with POST data.
        # We using reverse() to get the URL of the index view
        return HttpResponseRedirect(reverse(viewname='courses:course_details', args=(course.id,)))
    else:
        return HttpResponse("Invalid request")
    
def course_details(request, course_id):
    context = {}
    if request.method == 'GET':
        try:
            course = Course.objects.get(pk=course_id)
            context['course'] = course
            return render(request, 'courses/course_detail.html', context)
        except Course.DoesNotExist:
            raise Http404("Course does not exist")

courses/templates/courses/course_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'courses/courses.css' %}"
    />
  </head>
  <body>
    <div class="card">
      <h2>{{ course.name }}</h2>
      <h5>{{ course.description }}</h5>
      <h2>Lessons:</h2>
      {% for lesson in course.lesson_set.all %}
      <div class="card">
        <h5>Lesson {{ lesson.title}}</h5>
        <p>{{lesson.content}}</p>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

courses/templates/courses/course_list.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Course List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'courses/courses.css' %}" />
  </head>
  <body class="course-body">
    {% if courses %}
    <div class="container">
      {% for course in courses %}
      <div class="row">
        <img
          alt="img"
          src="{{ MEDIA_URL }}{{ course.image }}"
          width="360"
          height="360"
          class="column-33"
        />
        <div class="column-33">
          <h1 class="xlarge-font">{{ course.name }}</h1>
          <p class="course-paragraph">{{ course.description }}</p>
          <p>{{course.total_enrollment}}</p>
          <form action="{% url 'courses:enroll' course.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Enroll" />
          </form>
        </div>
      </div>
      {% endfor %}
      <hr class="course=separator" />
    </div>
    {% else %}
    <p>No courses are available.</p>
    {% endif %}
  </body>
</html>